import Foundation

/// Baked at build time so an install is verifiable on-device (More > About).
/// Regenerated by the build wrapper before each xcodebuild.
enum BuildStamp {
  static let commit = "ab55c85"
  static let commitCount = 34
  static let builtAt = "2026-06-21 20:58"

  static var summary: String {
    "#\(commitCount) · \(commit) · \(builtAt)"
  }
}
