import Foundation

/// Baked at build time so an install is verifiable on-device (More > About).
/// Regenerated by the build wrapper before each xcodebuild.
enum BuildStamp {
  static let commit = "a7ba5ef"
  static let commitCount = 40
  static let builtAt = "2026-06-21 21:26"

  static var summary: String {
    "#\(commitCount) · \(commit) · \(builtAt)"
  }
}
